apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-result-app
spec:
  containers:
    - name: worker-app
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTEGRES_USER
          value: "postgres"
        - name: POSTEGRES_PASSWORD
          value: "postgres"
